### ISSUE TITLE
Remove gulp dependency

### ISSUE THREAD

**Issue by AvraamMavridis** [AvraamMavridis/louis#1]

**Comment by stefanjudis** [comment]
Heyo - so, quick question, how do we want to proceed here?
Making a huge pull request can feel really bad...

Maybe you could provide a `.eslintrc` ( eslint is too good and covers also coding style which is really nice ) and a `.editorconfig`? I think this might be a good start for me not messing up with your preferred kind of writing code. :)

But I can also just bump in a huge PR. ;) 
Only want to avoid a feeling like me taking over - as this is not the case. :)

**Comment by AvraamMavridis** [comment]
Yep, agreed, I will do that. Its a bit difficult during the week, but I will definitely do that on (probably) Saturday or Sunday. :) :+1:

**Comment by AvraamMavridis** [comment]
@stefanjudis eslintrc and style-fixes for the rules added.  Maybe a PR for this issue include only the removal of the gulp related code and the necessary changes for that. Let me know your ideas and we can discuss anything else (and/or open related issues). :)

**Comment by stefanjudis** [comment]
:+1: 

One question - usually it's just `.eslintrc`, `.jshintrc`, ... - any reason for the `*.json`?

Cool - I think I'll give it a try soon'ish ( not sure if I'm able to make it today ).

What is your opinion on splitting ones more in `louis` and `louis-cli`. I did that for 2 projects so far and it worked out really good. See https://github.com/stefanjudis/credits-cli & https://github.com/stefanjudis/is-http2-cli.

Advantages of this approach:
- less dependencies for module users ( no cli stuff in there )
- ability to break api and have a major version bump of cli tool without the need of communicating a breaking change in the "plain module"

> Maybe a PR for this issue include only the removal of the gulp related code and the necessary changes for that.

Sounds good - I should just start with that or how is your preferred way? :bowtie:

**Comment by AvraamMavridis** [comment]
Hm, I am not sure why not just `.eslintrc`. I generated the rules using the `eslint cli` and I thought that my editor will recognize and highlight the `.json` better than `.eslintrc`. But I haven't tried the `.eslintrc`, I will check and rename it :)

I will take a look on the links and thought about the splitting, although I am not sure if it worth to split once more since this is a small tool right now, and I have some other ideas for improving it and adding but... yeah, have to find some time for that. But I will check it definitely :+1:  

Yeah you can start whenever you want :smiley: Let's remove the gulp dependency and then I have some ideas for improving it and I am open to any other idea of course.  Thx in advance! 

Feel free to add your name on the authors ;)

**Comment by stefanjudis** [comment]
> I will take a look on the links and thought about the splitting, although I am not sure if it worth to split once more since this is a small tool right now, and I have some other ideas for improving it and adding but... yeah, have to find some time for that. But I will check it definitely

Ja no pressure on that - just a personal flow and for me it makes sense. :)

> yeah you can start whenever you want :smiley: Let's remove the gulp dependency and then I have some ideas for improving it and I am open to any other idea of course. Thx in advance!

Cool - will let you know - when I start.

> Feel free to add your name on the authors ;)

Woooohooooo. Thx - maybe you can add me to collaborators then, too? Then I'm saving the forking stuff. :)

**Comment by AvraamMavridis** [comment]
:+1:

**Comment by AvraamMavridis** [comment]
I am closing this since the master has changed a lot.

**Comment by stefanjudis** [comment]
Oh man, sorry for the delay.

But you didn't remove gulp yet, did you?

**Comment by AvraamMavridis** [comment]
no worries :) I just had a little time this week and did some stuff. I  wanted to setup a workflow with es6 and travis etc. I havent remove `gulp-connect` dependency which is not needed actually. And there are some other issues as well. I will open them later during the day and if you have time and want you can grab whatever you want or submit any issue. :)

**Comment by stefanjudis** [comment]
>  I will open them later during the day and if you have time and want you can grab whatever you want or submit any issue. :)

I'm at cssclasses right now and it seems like I've got some time, because there are not enough students. :)

Give me a task and I'll takle it. ;)

But this issue is still valid though?

**Comment by stefanjudis** [comment]
Quick question? 

You didn't make me a collaborator, did you?
That would be great as it saves me the forking thing. :) :blush: 

If you don't like me to be that's fine. But I remember you said it's fine somewhere. :)

**Comment by AvraamMavridis** [comment]
Oh sorry forgot it. Done. Pls add also your name on package.json.

**Comment by stefanjudis** [comment]
Thanks. :)
