### ISSUE TITLE
Read parameters both from the command line or from a specified .json file

### ISSUE THREAD

**Issue by AvraamMavridis** [AvraamMavridis/louis#10]

**Comment by stefanjudis** [comment]
Do you have any prefered module for this?

I recently with https://github.com/sindresorhus/meow and it worked fine. :)

**Comment by AvraamMavridis** [comment]
Looks nice. Do you want to grab this?

**Comment by stefanjudis** [comment]
sure thing. :)
Maybe wanna assign me, so that we don't conflict?

**Comment by AvraamMavridis** [comment]
sure ;)

**Comment by AvraamMavridis** [comment]
I would not commit anything in the next 2-3 days, so probably we will not have any conflict. And of course no rush, take your time. I just had some free time and work a bit on it during the week.

**Comment by stefanjudis** [comment]
Should I leave the PR's pending or how do you want me to proceed?

**Comment by AvraamMavridis** [comment]
If you have time to write some tests as well feel free to merge it, no worries.

**Comment by stefanjudis** [comment]
Alright... it surely will be tested. ;)

So I'll jump into it right now. Please stop me when it's getting to crazy and too many PR's. :)

**Comment by AvraamMavridis** [comment]
:+1: go for it :smile:
