### ISSUE TITLE
Semantic versioning and v1

### ISSUE THREAD

**Issue by stefanjudis** [AvraamMavridis/louis#11]
Just a little note as I saw your milestone.

According to semantic versioning this module should start at `v1.0.0`. :)
There is no reason in starting with `v0.x` to mark it as unstable or anything as this will only break people builds.

**Comment by AvraamMavridis** [comment]
Yep, I agree. Actually at package.json is 1.0.0

**Comment by stefanjudis** [comment]
Ahh okay... Sorry then - was just looking at the set milestone
