### ISSUE TITLE
feedback first try

### ISSUE THREAD

**Issue by stefanjudis** [AvraamMavridis/louis#13]
Hey I started workin on it...
and it's kind of working now.

Would be great if you could provide feedback on branch `feature/13-feedback`.

<img width="707" alt="screenshot 2015-12-13 18 30 28" src="https://cloud.githubusercontent.com/assets/962099/11768264/a11c40e8-a1c7-11e5-9b25-0bf1b48329da.png">

**Comment by AvraamMavridis** [comment]
oh, looks really nice. I will play with it tomorrow morning or later tonight I let you know :smile: :+1:

**Comment by AvraamMavridis** [comment]
Its good :+1:  Only some missing spaces between parenthesis in the cli.js and to remove the `gulp-connect` dependency from the package.json, but in general looks very good :+1: :smile:

**Comment by stefanjudis** [comment]
Cool! Yeah it was the first try only. 

Surely will perform some cleanup still. :)
Will let you know, when I continue.

And one thing I noticed is that louis currently spawn `phantomas` via child process, this is not needed as `phantomas` has a node api available - but that's another issue then. :)

**Comment by AvraamMavridis** [comment]
I didnt know about the node api of phantomas, cool. 
If it is an easy issue I would like to share it with the https://twitter.com/yourfirstpr
so more people get involved. What do you think?

**Comment by stefanjudis** [comment]
> If it is an easy issue I would like to share it with the https://twitter.com/yourfirstpr
> so more people get involved. What do you think?

Never tried this. Your project your call. ;)

**Comment by AvraamMavridis** [comment]
Any update on the issue? I would like to move a bit forward the project during the holidays (after 25th) , shall I merge this and continue or you will work on that? ( no worries, just asking :) )

**Comment by stefanjudis** [comment]
Heyo...

Sorry for delay... If you like it merge and continue. As I'm going home for xmas I'm not sure, when I'll find time for it.

**Comment by AvraamMavridis** [comment]
No worries :) I will merge and if I found time during the holidays I will continue a bit.

Fröhliche Weihnachten ;)
