### ISSUE TITLE
"Themes" with different colors for the output on the console

### ISSUE THREAD

**Issue by AvraamMavridis** [AvraamMavridis/louis#8]

**Comment by stefanjudis** [comment]
Little recommendation:

Would be great to have different `reporters` for that which are place somewhere separately. 

See https://github.com/stefanjudis/credits-cli/tree/master/reporters.

This makes it easily testable and gives a nice way to extend it later on. :)

What do you think?

**Comment by AvraamMavridis** [comment]
Yep, agree, thats the plan. I want to investigate a bit more on that, and look what other tools are doing to present data.

**Comment by stefanjudis** [comment]
> I want to investigate a bit more on that, and look what other tools are doing to present data

Please share preferred way then. :bowtie:
